--- 
- 
  name: "Add the user "
  user: 
    group: root
    name: "{{ item }}"
    uid: 1040
    shell: /bin/bash
  with_items: "{{ users }}"  
    
- 
  name: "Create a 4096-bit SSH key for user"
  user: 
    generate_ssh_key: true
    name: "{{ item }}"
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  with_items: "{{ users }}"  